analyst: Jennifer Wenner
email: jennifer.wenner@conehealth.com
project_description: |-
  Using Cori et al to estimate the reproduction number (R) by county for NC.
website_keywords:
- Covid19
- Reproduction Number
- System Wide
# Optional For Scheduling
# https://crontab.guru/
# Use Eastern Standard Times
# Example Dag runs at 9:30am Daily
scheduled: yes # needs to run after NCDHHS data is updated; wednesdays try starting at 4:00pm
airflow_schedule:
  hour: '16'
  minute: '0'
  week_day: '3'
airflow_tags:
- R
- Covid-19
- Reproduction Number

